---

- hosts: localhost
  become: true
  gather_facts: false
  vars_files:
    - vars/wordpress_vault.yml
  roles:
    - { role: vagrant, tags: [vagrant] }

- hosts: wordpress
  become: true
  vars_files:
    - vars/wordpress.yml
    - vars/wordpress_vault.yml
  roles:
    - { role: nginx, tags: [nginx] }
    - { role: php, tags: [php] }
    - { role: wordpress, tags: [wordpress] }

- hosts: database
  become: true
  vars_files:
    - vars/wordpress.yml
    - vars/wordpress_vault.yml
  roles:
    - { role: mysql, tags: [mysql] }

- hosts: haproxy
  become: true
  roles:
    - { role: haproxy, tags: [haproxy] }

- name: install monitoring stack
  hosts: monitoring
  become: true
  vars_files:
    - vars/wordpress_vault.yml
  roles:
    - { role: prometheus, tags: [prometheus] }
    - { role: grafana, tags: [grafana] }

- name: install node-exporter
  hosts:
    - wordpress
    - database
    - haproxy
  become: true
  roles:
    - { role: node-exporter, tags: [node-exporter] }
