---

- name: update and install prometheus
  apt:
    name: prometheus
    state: latest
    update_cache: true
    cache_valid_time: 3600

- name: prometheus args
  template:
    src: prometheus.j2
    dest: /etc/default/prometheus
    mode: 0644
    owner: root
    group: root
  notify: restart_prometheus

- name: prometheus configuration file
  template:
    src: prometheus.yml.j2
    dest: "{{ prometheus_dir_configuration }}/prometheus.yml"
    mode: 0755
    owner: prometheus
    group: prometheus
  notify: reload_prometheus

- name: start prometheus
  systemd:
    name: prometheus
    state: started
    enabled: true

#- name: Configure prometheus static targets
#  copy:
#    content: |
#      {{ item.value | to_nice_yaml(indent=2, sort_keys=False) }}
#    dest: "{{ prometheus_config_dir }}/file_sd/{{ item.key }}.yml"
#    force: true
#    owner: root
#    group: prometheus
#    mode: 0640
#  with_dict: "{{ prometheus_targets }}"
#  when: prometheus_targets != {}